### ISSUE TITLE
ReferenceCCDAValidator has state

### ISSUE THREAD

**Issue by PeterTeunissen** [siteadmin/referenceccdavalidator#12]
ReferenceCCDAValidator class (which is a spring bean, and spring beans are singletons) keeps state in 

private boolean isValidationObjectiveMu2Type = false;

which makes it NOT threadsafe.

**Comment by drbgfc** [comment]
Hi Peter,
I appreciate the input. This is a rather simple scenario where we need a boolean which can be referenced locally and from another class (ReferenceCCDAValidationService). It is not static. It is not an issue for us. How would you suggest we handle it otherwise? Maybe you would like to make a suggestion or submit a simple PR?
