### ISSUE TITLE
Code Repository and Valueset Repository

### ISSUE THREAD

**Issue by ZacWisdom** [siteadmin/referenceccdavalidator#8]
In the install instructions, there are references to two repositories that should be downloaded. Code's (no attached filetype) and ValueSet (*.xsl filetype). There are no links to these repos, and if they exist on the web they are well hidden. Can you point in a direction to find these required files?

**Comment by andypardue** [comment]
I'd like to offer a "me too" on this issue raised by ZacWisdom. I'm having more than a little trouble figuring out if this project is actually something that an average developer could use or not. I'm hoping that a little more guidance could prove if this reference validator can help us solve a problem. I can't find the pre-built war file. I can build my own, but it won't deploy into a tomcat7. I'm guessing it is because the support configuration are not pre-deployed. I can't find the valueset and code_repository files. I'm not sure if I would know them if I were to stumble upon them.

Anyway, I have great hopes that this project will serve as a solution or guideline for us. Please, if at all possible, help fill in the blanks.

**Comment by Plow74** [comment]
We understand that getting the code systems and valuesets is one of the biggest pain points, if not the biggest. Code systems can be downloaded and used without a license. However, a licence is required to use valuesets and for this reason we do not distribute the code systems and valuesets. I have included a list of the code systems and valuesets we use - under /configuration on the develop branch now. We are working to provide better instructions on how to download the files and the necessary format the validator expects to import them - we have been able to help stand up multiple instances of the validator.
[codesystems.txt](https://github.com/siteadmin/referenceccdavalidator/files/807429/codesystems.txt)
[valuesets.txt](https://github.com/siteadmin/referenceccdavalidator/files/807428/valuesets.txt)
